Explain why get-cd-id exits when no CD is inserted

diff --git a/bin/media-get-cd-id b/bin/media-get-cd-id
--- a/bin/media-get-cd-id
+++ b/bin/media-get-cd-id
@@ -24,7 +24,12 @@ cd_output=$( mktemp )
 if [ -n "$MEDIA_TESTING_CD_QUERY_FILE" ]; then
     cat "$MEDIA_TESTING_CD_QUERY_FILE" > "$cd_output"
 else
-    cdparanoia --query 2> "$cd_output"
+    cdparanoia --query 2> "$cd_output" || true
+
+    if [ "$(tail -1 "$cd_output")" = 'Unable to open disc.' ]; then
+        echo "Unable to open disc."
+        exit 1
+    fi
 fi
 
 # shellcheck disable=SC2002
